# Generated by Django 3.2 on 2021-04-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prod', models.CharField(max_length=100)),
                ('Loc_name', models.CharField(max_length=100)),
                ('Quality', models.IntegerField()),
            ],
        ),
    ]
