# Generated by Django 3.2 on 2021-04-21 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0002_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='Quality',
            new_name='Quantity',
        ),
    ]
