# Generated by Django 3.2 on 2021-04-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0003_rename_quality_inventory_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='Loc_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
