# Generated by Django 3.2 on 2021-04-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0004_alter_inventory_loc_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Movement_id', models.CharField(max_length=100)),
                ('Prod_id', models.CharField(max_length=100)),
                ('Loc_From', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Loc_To', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('Quantity', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='Prod_id',
            field=models.CharField(default=111, max_length=100),
            preserve_default=False,
        ),
    ]
