# Generated by Django 3.2 on 2021-04-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0005_auto_20210421_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmovement',
            name='timestamp',
            field=models.DateField(blank=True, null=True),
        ),
    ]
