# Generated by Django 3.2 on 2021-04-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0006_alter_productmovement_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmovement',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='productmovement',
            name='Time_Mov',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='productmovement',
            name='Loc_From',
            field=models.CharField(max_length=100),
        ),
    ]
