# Generated by Django 3.2 on 2021-04-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0007_auto_20210421_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmovement',
            name='Time_Mov',
        ),
        migrations.AddField(
            model_name='productmovement',
            name='timestamp',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productmovement',
            name='Loc_From',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
